### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by promgamer** [AMWA-TV/nmos-content-model#1]
- [represen**t**ation](https://github.com/AMWA-TV/nmos-content-model/blame/25d499157beb8796fcff0b3cfc5b99ad92ce7f54/specifications/ContentModel.md#L45)
- [Univer**s**ally](https://github.com/AMWA-TV/nmos-content-model/blame/25d499157beb8796fcff0b3cfc5b99ad92ce7f54/specifications/ContentModel.md#L80)
- ["... according to ~~to~~ the type of Flow."](https://github.com/AMWA-TV/nmos-content-model/blame/25d499157beb8796fcff0b3cfc5b99ad92ce7f54/specifications/ContentModel.md#L101)
- [according to ~~to~~ the type of Source.](https://github.com/AMWA-TV/nmos-content-model/blame/25d499157beb8796fcff0b3cfc5b99ad92ce7f54/specifications/ContentModel.md#L128)

**Comment by peterbrightwell** [comment]
Corrected on v1.1-dev
